### ISSUE TITLE
Automated Testing Strategy for Mainnet with ADA-Free Scenarios

### ISSUE THREAD

**Issue by kneerose** [cardanoapi/govtool-test-reports#8]
#### Context
- Manual testing on the mainnet is time-consuming due to potential mainnet-specific bugs that may not occur on other networks. Currently, automatic testing is available on the preview network, where a test wallet can be used to perform on-chain and off-chain actions. However, on the mainnet, actions involving ADA spending cannot be automated as they involve real costs. Instead, we can focus on automated tests for the following scenarios on the mainnet: 

  - Visibility checks.
  - Wallet disconnected states.
  - Mobile responsiveness.
  - Wallet connection functionality.
  - Proposal discussion forum functionality (excluding the proposal submission part).

#### TODO
- [x] Brainstorm and list possible tests that can be conducted without spending actual ADA.
- [x] Review all test cases and separate **ADA-independent tests** into a different file for better organization
- [x] Brainstorm and set up a dedicated Playwright project structure for the mainnet, as many components currently depend on authentication or dRep setup.
- [x] Identify and skip tests that require ADA spending, running only those that do not involve real ADA transactions on the mainnet.
- [x] configure the network Id and use mainnet wallet for mainnet test
- [x] Run test in 'gov.tools'
- [x] Add a workflow dispatch mechanism for triggering Playwright automated tests on the mainnet.
- [x]  Add an Allure description to skipped tests explaining the reason for the skip.

**Comment by kneerose** [comment]
Mainnet Test allure Report [#136](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/136)
Preview Test allure Report [#137](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/137)

**Comment by kneerose** [comment]
- Mainnet skip test With allure description [example](https://cardanoapi.github.io/govtool-test-reports/govtool-frontend/140/#behaviors/9ac8de95e77713861f808e6170fefbb2/db27d90abb4811d6/)
- Automated test strategy [PR #2572](https://github.com/IntersectMBO/govtool/pull/2572)
- Mainnet test allure report [intersectmbo](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/242)
